openapi: 3.1.0
info:
  version: 1.5.6
  title: Upbit API
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: contact@example.com
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    업비트 API 문서 테스트
tags:
  - name: Accounts
    description: "Example Accounts"
servers:
  - url: https://api.upbit.com/v1
components:
  securitySchemes:
    authToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        입력한 파라미터에 맞는 JWT 입력
x-readme: # Readme Extension 적는 부분
  explorer-enabled: false # try it 버튼 활성(true)/비활성화(false)
  samples-languages: ["shell", "python", "java", "ruby"] # sample code 언어 선택
  # parameter-ordering: ["header", "path", "query", "cookie", "body", "form"] # 파라미터 순서 지정
paths:
  "/accounts":
    $ref: ./paths/accounts.yaml
  "/orders/chance":
    $ref: paths/orders_chance.yaml
